nome = input('Digite o seu nome: ').strip()
print(nome.upper())
print(nome.lower())
print(''.join(nome.split()))
#print(len(nome)-nome.count(' '))
prn = nome.split()
print(len(prn[0]))
#+print(nome.find(' '))
