frase = 'Curso em Video Python'
dividido = frase.split()
print(frase.lower().find('video'))
print(dividido)
print(dividido[0])
print(dividido[2][3])
print(frase[:13])
print(frase[13:])
print(frase[1:15:2])
print(frase.count('o'))
print(frase.upper().count('O'))
print(len(frase))
print(frase.replace('Python', 'Andorid'))
print('Curso' in frase)
print(frase.find('Curso'))
